feat:update ci-cd

diff --git a/.github/workflows/run-build.yml b/.github/workflows/run-build.yml
--- a/.github/workflows/run-build.yml
+++ b/.github/workflows/run-build.yml
@@ -99,7 +99,16 @@ jobs:
         run: |
           echo "Updating Kustomize with image tag: ${{ steps.build-image.outputs.image_sha }}"
           IMAGE_TAG="${{ steps.build-image.outputs.image_sha }}"
-          sed -i "s|abbass69/microservice:api-gateway.*|$IMAGE_TAG|" $KUSTOMIZATION_FILE
-          git add infra/development/k8s/${{ inputs.environment }}/kustomization.yaml
+          
+          KUSTOMIZATION_FILE="infra/development/k8s/kustomization.yaml"
+      
+          if [ ! -f "$KUSTOMIZATION_FILE" ]; then
+          echo "❌ ERROR: Kustomization file not found at $KUSTOMIZATION_FILE"
+          exit 1
+          fi
+
+          sed -i "s|abbass69/microservice:api-gateway.*|$IMAGE_TAG|" "$KUSTOMIZATION_FILE"
+          
+          git add "$KUSTOMIZATION_FILE"
           git commit -m "Update Kustomize with new image tag: $IMAGE_TAG"
           git push
